[process]
audio_frame_size_len=2496   # 48000 * 52ms = 2496 amostras por frame
audio_frame_hop_len=1248    # 48000 * 26ms = 1248 amostras por frame
sequence_size_len=10        # 10 frames por sequência
sequence_hop_len=1          # 1 frame de offset
audio_sample_rate=48000     # 48000Hz
snore_sample_rate=500       # 500Hz
n_mfcc=13                   # number of MFCCs